name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install libcap2 libcap-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - run: bundle exec rake test